name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: windows-latest

    steps:
    - name: Setting Environment Variables
      env:
        APPSETTINGS_PRODUCTION: ${{ secrets.APPSETTINGS_PRODUCTION }}
      run: |
        echo $env:APPSETTINGS_PRODUCTION > secret.json
        $secret = Get-Content -Raw secret.json
        pwd
        ls -Force
        Set-Content -Path "FoodDesire.AppSettings\appsettings.Production.json" -Value $secret
        Set-Content -Path "FoodDesire.AppSettings\appsettings.Development.json" -Value $secret
      shell: pwsh

    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build Src/FoodDesire.sln --configuration ${{ matrix.configuration }}

    - name: Run tests
      run: dotnet test Src/
